language: node_js

node_js:
  - node

services: mongodb

before_script:
  - npm install

cache:
  directories:
    - node_modules

script:
  - npm run test

deploy:
  provider: lambda
  function_name: switches
  region: 'us-east-1'
  runtime: nodejs12.x
  role: arn:aws:iam::877028087283:role/CS3219-OTOT-B-dev-us-east-1-lambdaRole
  handler_name: index.handler
  edge: true
  on:
    branch:
      - master